# Generated by Django 2.1.2 on 2018-10-16 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('numberOfVotes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='choicem',
            name='question_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rhApp.QuestionM'),
        ),
    ]
